Reorganizing

diff --git a/all_bash_profile b/all_bash_profile
--- a/all_bash_profile
+++ b/all_bash_profile
@@ -12,6 +12,50 @@ umask 002
 export TERMINFO="$HOME/.terminfo"
 
 #----------
+# Functions
+#----------
+
+# Extract function
+function extract(){
+  if [ -f $1 ] ; then
+    case $1 in
+        *.tar.bz2)   tar xvjf $1     ;;
+        *.tar.gz)    tar xvzf $1     ;;
+        *.bz2)       bunzip2 $1      ;;
+        *.rar)       unrar x $1      ;;
+        *.gz)        gunzip $1       ;;
+        *.tar)       tar xvf $1      ;;
+        *.tbz2)      tar xvjf $1     ;;
+        *.tgz)       tar xvzf $1     ;;
+        *.zip)       unzip $1        ;;
+        *.Z)         uncompress $1   ;;
+        *.7z)        7z x $1         ;;
+        *.xz)        xz -d $1         ;;
+        *)           echo "'$1' cannot be extracted via >extract<" ;;
+    esac
+  else
+    echo "'$1' is not a valid file"
+  fi
+}
+
+# Counts the Number of Columns in a File
+function num_cols(){
+  awk '{print NF}' $1 | sort -nu | tail -n 1
+}
+
+# Gets the first line of the tsv file and then returns each column as a separate
+# line
+function print_cols() {
+	head -n 1 $1 | tr '\t' '\n' | less -S
+}
+
+# Used in PS1
+parse_git_branch() {
+	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
+}
+
+
+#----------
 # Git
 #----------
 
@@ -31,10 +75,6 @@ fi
 # Make sure you have install base16-shell (https://github.com/chriskempson/base16-shell)
 BASE16_SHELL="${HOME}/.config/base16-shell/scripts/base16-default-dark.sh"
 [[ "$-" == *i* ]] && [[ -s ${BASE16_SHELL} ]] && source ${BASE16_SHELL}
-
-parse_git_branch() {
-	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
-}
 
 # Customize linux prompt
 export PS1="\n[\u@\h] \D{%F %T}\n \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\]\n$> "
@@ -87,43 +127,30 @@ fi
 # https://github.com/junegunn/fzf/issues/546
 bind "$(bind -s | grep __fzf_select | sed 's/\\C-t/\\C-f/')"
 
+
 #----------
-# Functions
+# Miniconda
 #----------
 
-# Extract function
-function extract(){
-  if [ -f $1 ] ; then
-    case $1 in
-        *.tar.bz2)   tar xvjf $1     ;;
-        *.tar.gz)    tar xvzf $1     ;;
-        *.bz2)       bunzip2 $1      ;;
-        *.rar)       unrar x $1      ;;
-        *.gz)        gunzip $1       ;;
-        *.tar)       tar xvf $1      ;;
-        *.tbz2)      tar xvjf $1     ;;
-        *.tgz)       tar xvzf $1     ;;
-        *.zip)       unzip $1        ;;
-        *.Z)         uncompress $1   ;;
-        *.7z)        7z x $1         ;;
-        *.xz)        xz -d $1         ;;
-        *)           echo "'$1' cannot be extracted via >extract<" ;;
-    esac
+# If conda is installed, add the bin folder to your PATH variable.
+# Check if the argcomplete conda package is available, if so enable tab 
+# complete (http://conda.pydata.org/docs/install/tab-completion.html)
+if [[ -d ${HOME}/miniconda3 ]]; then
+
+  echo "Found ${HOME}/miniconda3. Appending ${HOME}/miniconda3/bin to PATH"
+  export PATH=${HOME}/miniconda3/bin:${PATH}
+
+  # If the argcomplete conda package is available
+  conda list argcomplete | grep "argcomplete" > /dev/null
+  if [[ $? -eq 0 ]]; then
+    eval "$(register-python-argcomplete conda)"
   else
-    echo "'$1' is not a valid file"
+    echo "conda argcomplete package is not installed. Consider installing with 'conda install argcomplete'. This would allow for conda tab complete"
   fi
-}
 
-# Counts the Number of Columns in a File
-function num_cols(){
-  awk '{print NF}' $1 | sort -nu | tail -n 1
-}
+fi
 
-# Gets the first line of the tsv file and then returns each column as a separate
-# line
-function print_cols() {
-	head -n 1 $1 | tr '\t' '\n' | less -S
-}
+
 
 # For iTerm2 integration with shell
 # https://www.iterm2.com/documentation-shell-integration.html
